CREATE TABLE 고객(
고객id VARCHAR2(20) PRIMARY KEY,
성별 VARCHAR2(10) NOT NULL,
성명 VARCHAR2(20) NOT NULL,
비밀번호 CHAR(30) NOT NULL,
나이 NUMBER(5) NOT NULL,
고객_등급 VARCHAR2(10) NOT NULL,
마일리지 NUMBER(15) NOT NULL
);

CREATE TABLE 고객_연락처( 
고객id VARCHAR2 (20),
연락처 VARCHAR2 (20),
CONSTRAINT PK_고객_연락처 PRIMARY KEY(고객id,연락처),
CONSTRAINT FK_고객ID FOREIGN KEY(고객id) REFERENCES 고객(고객id)
);

CREATE TABLE 게시글(
글번호 NUMBER(10)PRIMARY KEY,
글내용 VARCHAR2(40),
글제목 VARCHAR2(20) NOT NULL,
작성일자 VARCHAR2(20) NOT NULL,
고객id VARCHAR2(20),
CONSTRAINT FK_게시글 FOREIGN KEY(고객id) REFERENCES 고객(고객id)
);


CREATE TABLE 공항(
공항_번호 CHAR(15),
공항_이름 VARCHAR2(10),
CONSTRAINT PK_공항 PRIMARY KEY(공항_번호)
);

CREATE TABLE 비행편(
비행편_코드 VARCHAR2(10) NOT NULL,
출발지 VARCHAR2(20),
도착지 VARCHAR2(20),
출발_날짜 CHAR(10),
도착_날짜 CHAR(10) NOT NULL,
공항_번호 CHAR(15) NOT NULL,
출발_시간 CHAR(10) NOT NULL,
도착_시간 CHAR(10) NOT NULL,
CONSTRAINT PK_비행편 PRIMARY KEY(비행편_코드),
CONSTRAINT FK_비행편1 FOREIGN KEY(공항_번호) REFERENCES 공항(공항_번호),
CONSTRAINT CHK_dates CHECK(출발_날짜=도착_날짜),
CONSTRAINT CHK_TIME CHECK(출발_시간<도착_시간)
);

CREATE TABLE 비행_요금(
요금id VARCHAR2(20),
비행편_코드 VARCHAR2(20),
이코노미석 number(20),
비지니스석 number(20),
퍼스트석 number(20),
CONSTRAINT PK_비행_요금 PRIMARY KEY(요금id,비행편_코드),
CONSTRAINT FK_비행_요금 FOREIGN KEY(비행편_코드) REFERENCES 비행편(비행편_코드)
);

CREATE TABLE 예약(
예약_번호 VARCHAR2(10) NOT NULL,
비행편_코드 VARCHAR2(20) NOT NULL,
고객id VARCHAR2(20) NOT NULL,
좌석번호 VARCHAR2(20) NOT NULL,
예약_날짜 VARCHAR2(20) NOT NULL,
여권_번호 NUMBER(20) NOT NULL UNIQUE,
CONSTRAINT PK_예약 PRIMARY KEY(예약_번호, 비행편_코드, 고객id),
CONSTRAINT FK_예약 FOREIGN KEY(비행편_코드) REFERENCES 비행편(비행편_코드),
CONSTRAINT FK_예약2 FOREIGN KEY(고객id) REFERENCES 고객(고객id)
);

CREATE TABLE 환불(
환불_사유_코드 VARCHAR2(20),
환불_사유 VARCHAR2(30),
CONSTRAINT PK_환불 PRIMARY KEY(환불_사유_코드)
);

CREATE TABLE 환불_요청(
환불_계좌_번호 VARCHAR2(20),
고객id VARCHAR2(20),
환불_사유_코드 VARCHAR2(20),
환불_은행 VARCHAR2(10),
CONSTRAINT PK_환불_요청 PRIMARY KEY(환불_계좌_번호, 고객id, 환불_사유_코드),
CONSTRAINT FK_환불_요청1 FOREIGN KEY(고객id) REFERENCES 고객(고객id),
CONSTRAINT FK_환불_요청2 FOREIGN KEY(환불_사유_코드) REFERENCES 환불(환불_사유_코드)
);

CREATE TABLE 항공사(
항공사id VARCHAR2(20),
항공사_이름 VARCHAR2(40),
항공사_홈페이지 VARCHAR2(40),
CONSTRAINT PK_항공사 PRIMARY KEY(항공사id)
);

CREATE TABLE 비행기(
비행기_번호 CHAR(40),
좌석수 NUMBER(5) NOT NULL,
항공사id VARCHAR2(40) NOT NULL,
CONSTRAINT PK_비행기 PRIMARY KEY(비행기_번호),
CONSTRAINT FK_비행기 FOREIGN KEY(항공사id) REFERENCES 항공사(항공사id),
CONSTRAINT CHK_좌석 CHECK(좌석수<=400),
CONSTRAINT CHK_비행기번호 CHECK(비행기_번호 LIKE '%-%')
);

CREATE TABLE 운행(
비행편_코드 VARCHAR2(20) NOT NULL,
비행기_번호 CHAR (40) NOT NULL,
CONSTRAINT PK_운행 PRIMARY KEY(비행편_코드, 비행기_번호),
CONSTRAINT FK_운행1 FOREIGN KEY(비행편_코드) REFERENCES 비행편(비행편_코드),
CONSTRAINT FK_운행2 FOREIGN KEY(비행기_번호) REFERENCES 비행기(비행기_번호)
);

